apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${IMAGE_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${IMAGE_NAME}
  template:
    metadata:
      labels:
        app: ${IMAGE_NAME}
    spec:
      containers:
        - name: ${IMAGE_NAME}
          image: ${HOST_REGISTRY}/${IMAGE_NAME}:${IMAGE_TAG}
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: ${PORT_CONTAINER}
