apiVersion: v1
kind: Service
metadata:
  name: ${IMAGE_NAME}
spec:
  type: NodePort
  selector:
    app: ${IMAGE_NAME}
  ports:
    - port: ${SERVICE_PORT}
      targetPort: ${SERVICE_PORT}
      nodePort: ${CONTAINER_PORT}
