apiVersion: v1
kind: Service
metadata:
  name: organix-app-service
  namespace: default
spec:
  selector:
    app: organix-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: NodePort
