apiVersion: v1
kind: Service
metadata:
  name: ${IMAGE_NAME}
spec:
  type: NodePort
  selector:
    app: ${IMAGE_NAME}
  ports:
    - port: ${PORT_SERVICE}
      targetPort: ${PORT_SERVICE}
      nodePort: ${PORT_CONTAINER}
